language: php
sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

matrix:
    fast_finish: true
    include:
        - php: 7.4snapshot
          env: SKELETON_VERSION="^3.4"
        - php: 7.4snapshot
          env: SKELETON_VERSION="^4.0"

before_install:
    - phpenv config-rm xdebug.ini || true

install:
    - composer create-project "symfony/skeleton:${SKELETON_VERSION}" coka
    - cd coka

script:
    - composer req --ignore-platform-reqs coka/rest-request-validator-bundle
