services:
    oka_rest_request_validator.error_response.factory:
        class: Oka\RESTRequestValidatorBundle\Service\ErrorResponseFactory
        arguments: ['@translator', '']

    Oka\RESTRequestValidatorBundle\Service\ErrorResponseFactory:
        alias: oka_rest_request_validator.error_response.factory
        public: true

# Listener
    Oka\RESTRequestValidatorBundle\EventListener\AnnotationListener:
        arguments: ['@annotations.cached_reader', '@validator', '@translator', '@oka_rest_request_validator.error_response.factory', '@logger']
        tags:
          - {name: kernel.event_listener, event: kernel.controller, method: onKernelController}
          - {name: monolog.logger, channel: request}

    oka_rest_request_validator.response.event_listener:
        class: Oka\RESTRequestValidatorBundle\EventListener\ResponseListener
        tags:
          - {name: kernel.event_listener, event: kernel.response, method: onKernelResponse}
